---
title: "编译器错误 CS1626 | Microsoft Docs"
ms.date: "2015-07-20"
ms.prod: ".net"
ms.technology: 
  - "devlang-csharp"
ms.topic: "article"
f1_keywords: 
  - "CS1626"
dev_langs: 
  - "CSharp"
helpviewer_keywords: 
  - "CS1626"
ms.assetid: 3ba03383-eb24-4fd8-bf40-8b0f7d6baf0d
caps.latest.revision: 6
author: "BillWagner"
ms.author: "wiwagn"
caps.handback.revision: 6
---
# 编译器错误 CS1626
无法在包含 catch 子句的 Try 块体中生成值  
  
 如果有一个 catch 子句与 try 块关联，该 try 块内不允许有 yield 语句。 若要避免此错误，请将 yield 语句移到 catch 子句的外部。  
  
 下面的示例生成 CS1626：  
  
```  
// CS1626.cs using System.Collections; class C : IEnumerable { public IEnumerator GetEnumerator() { try { yield return this;  // CS1626 } catch { } } } public class CMain { public static void Main() { } }  
  
```