---
title: "“Throw”语句在“Catch”语句外或“Finally”语句内不能省略操作数 | Microsoft Docs"
ms.date: "2015-07-20"
ms.prod: ".net"
ms.technology: 
  - "devlang-visual-basic"
ms.topic: "article"
f1_keywords: 
  - "vbc30666"
  - "bc30666"
helpviewer_keywords: 
  - "BC30666"
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
caps.latest.revision: 8
author: "stevehoag"
ms.author: "shoag"
caps.handback.revision: 8
---
# “Throw”语句在“Catch”语句外或“Finally”语句内不能省略操作数
`Catch` 语句外的 `Throw` 语句必须提供异常对象的名称。  
  
 **错误 ID：**BC30666  
  
### 更正此错误  
  
1.  指定派生自 `System.Exception` 的异常对象的名称。  
  
2.  重构代码，以便 `Throw` 语句位于 `Catch` 块中。  
  
## 请参阅  
 [Throw 语句](../../visual-basic/language-reference/statements/throw-statement.md)   
 [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)   
 [Visual Basic 中的异常类](http://msdn.microsoft.com/zh-cn/9aac396f-34ca-4afb-8e6c-e523cb690ba9)   
 [Visual Basic 中的异常与错误处理](http://msdn.microsoft.com/zh-cn/3e351e73-cf23-40ab-8b60-05794160529e)